-- Examples of queries for Power_BI
--1
SELECT
	VIDEO_DETAILS.VIDEO_TITLE,
	VIDEO.VIEW_COUNT,
	VIDEO.LIKE_COUNT,
	VIDEO.COMMENT_COUNT,
	CHANNEL.CHANNEL_TITLE,
	CHANNEL.SUBSCRIBERS_COUNT
FROM VIDEO
JOIN CHANNEL ON VIDEO.CHANNEL_ID = CHANNEL.YT_CHANNEL_ID
JOIN VIDEO_DETAILS ON VIDEO.VIDEO_ID = VIDEO_DETAILS.YT_VIDEO_ID
WHERE CAST(VIDEO_DETAILS.PUBLISHED_AT AS DATE) = CAST('2024-02-05' AS DATE)
--2
SELECT
	VIDEO_DETAILS.VIDEO_TITLE,
	VIDEO.VIEW_COUNT,
	VIDEO.LIKE_COUNT,
	VIDEO.COMMENT_COUNT,
	CHANNEL.CHANNEL_TITLE,
	CHANNEL.SUBSCRIBERS_COUNT
FROM VIDEO
JOIN CHANNEL ON VIDEO.CHANNEL_ID = CHANNEL.YT_CHANNEL_ID
JOIN VIDEO_DETAILS ON VIDEO.VIDEO_ID = VIDEO_DETAILS.YT_VIDEO_ID
WHERE CHANNEL.SUBSCRIBERS_COUNT = 12345
--3
SELECT
	VIDEO_DETAILS.VIDEO_TITLE,
	VIDEO.VIEW_COUNT,
	VIDEO.LIKE_COUNT,
	VIDEO.COMMENT_COUNT,
	CHANNEL.CHANNEL_TITLE,
	CHANNEL.SUBSCRIBERS_COUNT
FROM VIDEO
JOIN CHANNEL ON VIDEO.CHANNEL_ID = CHANNEL.YT_CHANNEL_ID
JOIN VIDEO_DETAILS ON VIDEO.VIDEO_ID = VIDEO_DETAILS.YT_VIDEO_ID
WHERE CHANNEL.CHANNEL_TITLE = 'asdf'
--4
SELECT
	VIDEO_DETAILS.VIDEO_TITLE,
	VIDEO.VIEW_COUNT,
	VIDEO.LIKE_COUNT,
	VIDEO.COMMENT_COUNT,
	CHANNEL.CHANNEL_TITLE,
	CHANNEL.SUBSCRIBERS_COUNT
FROM VIDEO
JOIN CHANNEL ON VIDEO.CHANNEL_ID = CHANNEL.YT_CHANNEL_ID
JOIN VIDEO_DETAILS ON VIDEO.VIDEO_ID = VIDEO_DETAILS.YT_VIDEO_ID
WHERE VIDEO_DETAILS.VIDEO_TITLE IN ('%Power Bi%')
--5
SELECT
	VIDEO_DETAILS.VIDEO_TITLE,
	VIDEO_DETAILS.DURATION,
	VIDEO.VIEW_COUNT,
	VIDEO.LIKE_COUNT,
	VIDEO.COMMENT_COUNT,
	CHANNEL.CHANNEL_TITLE,
	CHANNEL.SUBSCRIBERS_COUNT
FROM VIDEO
JOIN CHANNEL ON VIDEO.CHANNEL_ID = CHANNEL.YT_CHANNEL_ID
JOIN VIDEO_DETAILS ON VIDEO.VIDEO_ID = VIDEO_DETAILS.YT_VIDEO_ID
WHERE CONVERT(TIME, DATEADD(SECOND, VIDEO_DETAILS.DURATION, 0)) >  PARSE('00:23:11' AS TIME)
ORDER BY VIDEO_DETAILS.DURATION
--6
SELECT
	D.VIDEO_TITLE,
    D.CREATED_AT,
    D.VIEW_COUNT,
    CASE WHEN D.PREVDATE IS NULL THEN 0
         ELSE D.VIEW_COUNT - D.VIEW_COUNT
    END AS DAILYGROWTH
FROM (
    SELECT
		VIDEO_DETAILS.VIDEO_TITLE,
        VIDEO.CREATED_AT,
        VIDEO.VIEW_COUNT,
        LAG(VIDEO.VIEW_COUNT, 1) OVER (ORDER BY VIDEO.CREATED_AT) AS PREVDATE
    FROM VIDEO
	JOIN CHANNEL ON VIDEO.CHANNEL_ID = CHANNEL.YT_CHANNEL_ID
	JOIN VIDEO_DETAILS ON VIDEO.VIDEO_ID = VIDEO_DETAILS.YT_VIDEO_ID
) AS D
ORDER BY D.CREATED_AT;